apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: shinyproxy
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    kubernetes.io/ingress.class: traefik-public
    traefik.frontend.rule.type: PathPrefixStrip
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
spec:
  rules:
    - host: "shinyproxy.aksonazure.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: shinyproxy
              servicePort: 8080
