# Source: shinyproxy/templates/rbac.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "create", "delete"]